export '/screens/onbording/views/onbording_screnn.dart';
// export '../screens/auth/login_screen.dart';
// export '/screens/auth/views/password_recovery_screen.dart';
// export '/screens/auth/views/signup_screen.dart';
export '/route/route_constants.dart';
export '/screens/bookmark/views/bookmark_screen.dart';
export '/screens/discover/views/discover_screen.dart';
export '/screens/home/views/home_screen.dart';
export '/screens/on_sale/views/on_sale_screen.dart';
export '/screens/product/views/product_details_screen.dart';
export '/screens/search/views/search_screen.dart';
export '/screens/cart/views/cart_screen.dart';
export '/screens/notification/view/enable_notification_screen.dart';
export '/screens/notification/view/no_notification_screen.dart';
export '/screens/notification/view/notification_ontions_screen.dart';
export '/screens/notification/view/notificatios_screen.dart';
export '/screens/order/views/order_confirmation_screen.dart';
export '/screens/preferences/views/preferences_screen.dart';
export '/screens/wallet/views/empty_wallet_screen.dart';
export '/screens/wallet/views/wallet_screen.dart';
export '/screens/profile/views/profile_screen.dart';
export '/screens/user_info/views/user_info_screen.dart';
export '/screens/home/views/components/product_screen.dart'; // غيّر المسار حسب مكان الملف
export '/screens/auth/login_screen.dart';
export '/screens/auth/VerificationCodeScreen.dart';
export '/screens/auth/complete_profile_screen.dart';
export '../screens/checkout/checkout_screen.dart';
